### PR TITLE
PS Amonkhet

### PR DESCRIPTION
**Pull request by TheGiddyLimit**

### CODE REVIEW

**Comment by astranauta** [comment]
We're gonna have to start paying you for doing our job for us.

**Comment by TheGiddyLimit** [comment]
Happy to help; fuck the need for an encyclopedic knowledge of UA PDFs. 

That being said, data entry's pretty boring, are there any tools I should know about to make this quicker (besides the bestiary JSON parser 👌👌)?

Unrelatedly, thoughts on rewriting data structure/javascript? Some (probably all) of this stuff is seriously hacky (tables within text/psionics are especially bad), I'm sure I could find time to clean some of it up.

**Comment by astranauta** [comment]
Nah, it's mostly just copy-pasting the relevant entries and then filling them out accurately. I know the pain.

We've been discussing rewriting the code for a little while now, or at least it's been in our heads as an option. Our host is offering a free server to put this on, so if you'd like to discuss it with her and I further, I could pass you a link to our Discord server.

**Comment by TheGiddyLimit** [comment]
Sure, I'd love to get to know my employers. Send it to 2687wysdab1yb at gmail.com.

**Pull request merged**
